### ISSUE TITLE
Heap Sort in GoLang

### ISSUE THREAD

**Issue by mayankagwl** [nikochiko/cool-algos#35]
Implement the Heap Sort Algorithm in GoLang

**Comment by mayankagwl** [comment]
@nikochiko please assign it to me

**Comment by nikochiko** [comment]
Hey, you're already assigned to #34 . Can you finish that first? 
Till then the issue is open for all

**Comment by mayankagwl** [comment]
@nikochiko Can I work on this now

**Comment by nikochiko** [comment]
Sure! Assigned

**Comment by mayankagwl** [comment]
@nikochiko Raised PR https://github.com/nikochiko/cool-algos/pull/58
