### ISSUE TITLE
changes to readme

### ISSUE THREAD

**Issue by hnishal** [nikochiko/cool-algos#62]
I can make the readme better organized, with table of content, direct links and stats

**Comment by nikochiko** [comment]
After some thought I have decided that it's best that this project not count towards Hacktoberfest now onwards. Accordingly, I have not added the "Hacktoberfest" topic to the repo as is required by new Hacktoberfest rules. Your old PRs would still count towards it but any new PRs from now would not.

If you still want to contribute, you are welcome

**Comment by hnishal** [comment]
To be really true with you, I dont care about hacktoberfest.
